name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # Update ke versi 22 sesuai kebutuhan Capacitor
          cache: 'npm'

      - name: Install Dependencies
        run: npm install  # Menggunakan install agar lock file sinkron otomatis

      - name: Build Proyek
        run: npm run build

      - name: Deploy ke Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SI_ELANG_LEBONG }}'
          channelId: live
          projectId: si-elang-lebong